name: hsfm
channels:
  - conda-forge
dependencies:
  - python==3.11
  - affine
  - altair
  - anyio
  - appnope
  - argon2-cffi
  - argon2-cffi-bindings
  - arrow
  - asttokens
  - async-lru
  - attrs
  - babel
  - beautifulsoup4
  - bleach
  - blosc
  - branca
  - brotli
  - brotli-bin
  - brotli-python
  - bzip2
  - c-ares
  - ca-certificates
  - cached-property
  - cached_property
  - cairo
  - certifi
  - cffi
  - cfitsio
  - charset-normalizer
  - click
  - click-plugins
  - cligj
  - colorama
  - comm
  - contourpy
  - cycler
  - debugpy
  - decorator
  - defusedxml
  - entrypoints
  - exceptiongroup
  - executing
  - expat
  - fiona
  - folium
  - font-ttf-dejavu-sans-mono
  - font-ttf-inconsolata
  - font-ttf-source-code-pro
  - font-ttf-ubuntu
  - fontconfig
  - fonts-conda-ecosystem
  - fonts-conda-forge
  - fonttools
  - fqdn
  - freetype
  - freexl
  - gdal
  - geopandas
  - geopandas-base
  - geos
  - geotiff
  - geoutils==0.0.8
  - gettext
  - giflib
  - hdf4
  - hdf5
  - icu
  - idna
  - importlib-metadata
  - importlib_metadata
  - importlib_resources
  - ipykernel
  - ipython
  - ipywidgets
  - isoduration
  - jedi
  - jinja2
  - joblib
  - json-c
  - json5
  - jsonpointer
  - jsonschema
  - jsonschema-specifications
  - jsonschema-with-format-nongpl
  - jupyter
  - jupyter-lsp
  - jupyter_client
  - jupyter_console
  - jupyter_core
  - jupyter_events
  - jupyter_server
  - jupyter_server_terminals
  - jupyterlab
  - jupyterlab_pygments
  - jupyterlab_server
  - jupyterlab_widgets
  - kealib
  - kiwisolver
  - krb5
  - lcms2
  - lerc
  - libabseil
  - libaec
  - libarchive
  - libblas
  - libboost-headers
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcblas
  - libcrc32c
  - libcurl
  - libcxx
  - libdeflate
  - libedit
  - libev
  - libexpat
  - libffi
  - libgdal
  - libgfortran
  - libgfortran5
  - libglib
  - libgoogle-cloud
  - libgrpc
  - libiconv
  - libjpeg-turbo
  - libkml
  - liblapack
  - libnetcdf
  - libnghttp2
  - libopenblas
  - libpng
  - libpq
  - libprotobuf
  - libre2-11
  - librttopo
  - libsodium
  - libspatialindex
  - libspatialite
  - libsqlite
  - libssh2
  - libtiff
  - libwebp-base
  - libxcb
  - libxml2
  - libzip
  - libzlib
  - llvm-openmp
  - lz4-c
  - lzo
  - mapclassify
  - markupsafe
  - matplotlib-base
  - matplotlib-inline
  - minizip
  - mistune
  - munch
  - munkres
  - nbclient
  - nbconvert
  - nbconvert-core
  - nbconvert-pandoc
  - nbformat
  - ncurses
  - nest-asyncio
  - networkx
  - notebook
  - notebook-shim
  - nspr
  - nss
  - numpy
  - openjpeg
  - openssl
  - overrides
  - packaging
  - pandas
  - pandoc
  - pandocfilters
  - parso
  - pcre2
  - pexpect
  - pickleshare
  - pillow
  - pip
  - pixman
  - pkgutil-resolve-name
  - platformdirs
  - poppler
  - poppler-data
  - postgresql
  - proj
  - prometheus_client
  - prompt-toolkit
  - prompt_toolkit
  - psutil
  - pthread-stubs
  - ptyprocess
  - pure_eval
  - pycparser
  - pygments
  - pyobjc-core
  - pyobjc-framework-cocoa
  - pyparsing
  - pyproj
  - pysocks
  - python-dateutil
  - python-fastjsonschema
  - python-json-logger
  - python-tzdata
  - python_abi
  - pytz
  - pyyaml
  - pyzmq
  - qtconsole-base
  - qtpy
  - rasterio
  - re2
  - readline
  - referencing
  - requests
  - rfc3339-validator
  - rfc3986-validator
  - richdem
  - rioxarray
  - rpds-py
  - rtree
  - scikit-learn
  - scipy
  - send2trash
  - setuptools
  - shapely
  - six
  - snappy
  - sniffio
  - snuggs
  - soupsieve
  - sqlite
  - stack_data
  - terminado
  - threadpoolctl
  - tiledb
  - tinycss2
  - tk
  - tomli
  - toolz
  - tornado
  - tqdm
  - traitlets
  - types-python-dateutil
  - typing-extensions
  - typing_extensions
  - typing_utils
  - tzcode
  - tzdata
  - uri-template
  - uriparser
  - urllib3
  - wcwidth
  - webcolors
  - webencodings
  - websocket-client
  - wheel
  - widgetsnbextension
  - xarray
  - xerces-c
  - xorg-libxau
  - xorg-libxdmcp
  - xyzservices
  - xz
  - yaml
  - zeromq
  - zipp
  - zlib
  - zstd
  - pip:
    - setuptools-scm