# Mt Baker
# Prepare all images
# 
# This notebook reorganizes/moves all the photos generated in the previous two notebooks. Two metashape CSV files
# are also generated, they are both generated by combining the separate versions generated for the EE and NAGAP 
# images in the previous two notebooks. 

# %%

import os
import shutil
import pandas as pd
import geopandas as gpd

# %%
# Required inputs:
main_directory = '/data2/elilouis/timesift/baker-ee-many/'

image_metadata_df = pd.read_csv(os.path.join(main_directory, 'combined_image_metadata.csv'))
metashape_metadata_df = pd.read_csv(os.path.join(main_directory, 'combined_metashape_metadata.csv'))



selected_images_gdf = gpd.read_file(os.path.join(main_directory, 'mixed_timesift', 'timesifted_image_footprints_manual_photos_removed.geojson'))
# %%
image_metadata_df = image_metadata_df[
    image_metadata_df.fileName.isin(selected_images_gdf.filename)
]

metashape_metadata_df = metashape_metadata_df[
    metashape_metadata_df.image_file_name.isin(selected_images_gdf.filename + '.tif')
]
# %%
image_metadata_df.to_csv(
    os.path.join(main_directory, 'combined_image_metadata_manual_selection.csv'),
    index=False
)
metashape_metadata_df.to_csv(
    os.path.join(main_directory, 'combined_metashape_manual_selection.csv'),
    index=False
)
# %%
